# Generated by Django 4.2.4 on 2023-11-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_log_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
