# Generated by Django 4.2.4 on 2023-11-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_requestcontext_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestcontext',
            options={'ordering': ('-created_at',)},
        ),
    ]
