# Generated by Django 4.2.4 on 2023-11-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_requestcontext_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('-created_at',)},
        ),
    ]
